apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/${{ values.namespaceName }}-namespace.yaml
  - ../../base/${{ values.namespaceName }}-resource-quota.yaml
  - ../../base/${{ values.namespaceName }}-role.yaml
